# Generated by Django 5.0.2 on 2024-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_business_business_pictures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_name_and_tags',
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='business_pictures',
            field=models.ImageField(default='', upload_to='business_pictures'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='business_tags',
            field=models.JSONField(default=dict),
        ),
    ]
