# Generated by Django 5.0.2 on 2024-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_business_business_address_business_business_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='directions_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
