# Generated by Django 5.0.2 on 2024-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_business_hours_of_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_pictures',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
