# Generated by Django 5.0.2 on 2024-03-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_business_business_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_barcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
