# Generated by Django 5.0.2 on 2024-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_business_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
