# Generated by Django 5.0.2 on 2024-03-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_business_business_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_pictures',
        ),
        migrations.AddField(
            model_name='business',
            name='business_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_video_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Video'),
        ),
    ]
