# Generated by Django 5.0.2 on 2024-03-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_business_uid_business_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_barcode_dates',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
