# Generated by Django 5.0.2 on 2024-05-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_business_business_barcode_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_reviews_summary',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
